
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const CHANGE_TITLE = 'CHANGE_TITLE';

export const REQUEST_STORYSET_LIST = 'REQUEST_STORYSET_LIST';
export const FETCH_STORYSET_LIST = 'FETCH_STORYSET_LIST';
export const RECEIVE_STORYSET_LIST = 'RECEIVE_STORYSET_LIST';

export const LOAD_LOCAL_STORYSET = 'LOAD_LOCAL_STORYSET';
export const UPDATE_LOCAL_STORYSET = 'UPDATE_LOCAL_STORYSET';
